import { test, expect } from '@playwright/test';

test.describe('Timeline Component E2E', () => {

    // --- HELPER FUNCTION FOR GRAPHQL MOCKING ---
    const mockScriptTimelineGraphql = async (
        page: any,
        options: { paragraphs: any[], visibility?: string }
    ) => {
        await page.route('**/graphql', async (route: any) => {
            const request = route.request();

            // Handle CORS Preflight
            if (request.method() === 'OPTIONS') {
                return route.fulfill({ status: 200, headers: { 'Access-Control-Allow-Origin': '*' } });
            }

            if (request.method() === 'POST') {
                const postData = request.postDataJSON();

                if (postData && postData.operationName === 'GetScriptById') {
                    return route.fulfill({
                        status: 200,
                        contentType: 'application/json',
                        headers: { 'Access-Control-Allow-Origin': '*' },
                        body: JSON.stringify({
                            data: {
                                getScriptById: {
                                    __typename: 'Script',
                                    id: 'script-123',
                                    visibility: options.visibility || 'PUBLIC',
                                    paragraphs: options.paragraphs
                                }
                            }
                        })
                    });
                }
            }
            await route.fallback();
        });
    };

    // Standard Mock Data
    const standardParagraphs = [
        {
            __typename: 'Paragraph',
            id: 'p1',
            text: 'The ship descended through the **clouds**, fire licking its hull.',
            createdAt: 1704153600000, // Newer
            author: { __typename: 'User', name: 'Jane SciFi' }
        },
        {
            __typename: 'Paragraph',
            id: 'p2',
            text: 'Captain Reynolds braced for impact. "Hold on!" he shouted.',
            createdAt: 1704067200000, // Older
            author: { __typename: 'User', name: 'John Doe' }
        }
    ];

    // Note: Update this URL to match exactly where your Timeline outlet is rendered!
    const PAGE_URL = '/timeline/script-123';

    test('should load timeline, sort by newest first, and render Markdown', async ({ page }) => {
        await mockScriptTimelineGraphql(page, { paragraphs: standardParagraphs });
        await page.goto(PAGE_URL);

        // 1. Verify authors and timestamps are rendered
        await expect(page.getByText('Jane SciFi')).toBeVisible();
        await expect(page.getByText('John Doe')).toBeVisible();

        // 2. Verify sorting (Jane's paragraph is newer, so it should appear FIRST in the DOM)
        const links = page.locator('a[href^="/contribution/script-123/"]');
        await expect(links).toHaveCount(2);
        await expect(links.nth(0)).toContainText('Jane SciFi'); // Newest first
        await expect(links.nth(1)).toContainText('John Doe');   // Oldest second

        // 3. Verify Markdown parsing (Look for the bold `<strong>` tag generated by "**.**")
        const strongTag = page.locator('strong', { hasText: 'clouds' });
        await expect(strongTag).toBeVisible();
    });

    test('should filter paragraphs via search and apply highlight <mark> tags', async ({ page }) => {
        await mockScriptTimelineGraphql(page, { paragraphs: standardParagraphs });
        await page.goto(PAGE_URL);

        // 1. Search for a specific word
        const searchInput = page.getByPlaceholder('Search timeline...');
        await searchInput.fill('Reynolds');

        // 2. Verify John's paragraph stays, but Jane's disappears
        await expect(page.getByText('Captain Reynolds braced')).toBeVisible();
        await expect(page.getByText('Jane SciFi')).not.toBeVisible();

        // 3. Verify your custom `highlightContent` regex wrapped the word in a <mark> tag!
        const highlightedText = page.locator('mark', { hasText: 'Reynolds' });
        await expect(highlightedText).toBeVisible();
        await expect(highlightedText).toHaveClass(/bg-amber-500/);
    });

    test('should show empty state when there are no contributions', async ({ page }) => {
        await mockScriptTimelineGraphql(page, { paragraphs: [] });
        await page.goto(PAGE_URL);

        // Verify empty state placeholder
        await expect(page.getByRole('heading', { name: 'No contributions yet' })).toBeVisible();

        // The Search bar should NOT be visible when the database is completely empty
        await expect(page.getByPlaceholder('Search timeline...')).not.toBeVisible();
    });

    test('should show no results found state when search does not match anything', async ({ page }) => {
        await mockScriptTimelineGraphql(page, { paragraphs: standardParagraphs });
        await page.goto(PAGE_URL);

        // Search for gibberish
        const searchInput = page.getByPlaceholder('Search timeline...');
        await searchInput.fill('Godzilla');

        // Verify the SearchX placeholder appears
        await expect(page.getByRole('heading', { name: 'No results found' })).toBeVisible();
        await expect(page.getByText('We couldn\'t find any results')).toBeVisible();
    });

    test('should hide Contribute buttons when script visibility is Archived', async ({ page }) => {
        // 1. Pass 'archived' as the visibility state
        await mockScriptTimelineGraphql(page, {
            paragraphs: standardParagraphs,
            visibility: 'Archived'
        });

        await page.goto(PAGE_URL);

        // Verify the timeline loads normally
        await expect(page.getByText('Jane SciFi')).toBeVisible();

        // 2. Verify the Header variant of the ContributeModal is HIDDEN
        // Since we don't know the exact text of your modal button, we look for the generic trigger
        // Make sure to adjust the name if your button says something specific like "Add Contribution"
        const contributeButton = page.getByRole('button', { name: /contribute|submit|new/i });
        await expect(contributeButton).not.toBeVisible();
    });

});