import express from 'express';
import http from 'http';
import cors from 'cors';
import { json } from 'body-parser';
import { ApolloServer } from '@apollo/server';
import { typeDefs } from '../../graphql/typedefs/typedefs';
import { expressMiddleware } from '@apollo/server/express4';
import { resolvers } from '../../graphql/resolvers/resolvers';
import { connectDB, disconnectDB } from '../../database/database';
import { MongoDBContainer, StartedMongoDBContainer } from '@testcontainers/mongodb';

interface MyContext {
    req: any;
    user: any;
    redis: any;
}

let httpServer: http.Server;
let apolloServer: ApolloServer<MyContext>;
let mongoContainer: StartedMongoDBContainer;

export const startTestServer = async (port: number = 4000): Promise<string> => {
    // 1. Spin up the MongoDB Testcontainer
    console.log('⏳ Starting MongoDB Testcontainer...');
    mongoContainer = await new MongoDBContainer("mongo:6.0.11").start();

    // Get the dynamic URI generated by the container (e.g., mongodb://localhost:54321)
    const uri = mongoContainer.getConnectionString();

    // 2. Connect your Mongoose instance to the container
    await connectDB(uri);

    const app = express();
    httpServer = http.createServer(app);

    // 3. Initialize Apollo Server with your actual schema
    apolloServer = new ApolloServer({
        typeDefs,
        resolvers,
    });

    await apolloServer.start();

    // 4. Mount Apollo Server to Express
    app.use(
        '/graphql',
        cors<cors.CorsRequest>(),
        json(),
        expressMiddleware(apolloServer, {
            context: async ({ req }) => {
                return {
                    req,
                    user: { id: 'test-runner', role: 'ADMIN' },
                    redis: {} as any
                };
            },
        })
    );

    // 5. Start listening on the specified port
    return new Promise((resolve) => {
        httpServer.listen(port, () => {
            console.log(`🚀 Test Server ready at http://localhost:${port}/graphql`);
            resolve(`http://localhost:${port}`);
        });
    });
};

export const stopTestServer = async () => {
    // 1. Shut down Apollo and Express
    if (apolloServer) {
        await apolloServer.stop();
    }
    if (httpServer) {
        httpServer.close();
    }

    // 2. Disconnect Mongoose from the database safely
    await disconnectDB();

    // 3. Stop and destroy the Docker container
    if (mongoContainer) {
        await mongoContainer.stop();
        console.log('🛑 MongoDB Testcontainer stopped and destroyed.');
    }

    console.log('🛑 Test Server stopped.');
};