import path from 'path';
import { Verifier } from '@pact-foundation/pact';
import { afterAll, beforeAll, describe, it } from 'vitest';
import { startTestServer, stopTestServer } from './pace_server';

describe('Pact Verification', () => {
    let serverUrl: string;

    beforeAll(async () => {
        serverUrl = await startTestServer(4000);
    });

    afterAll(async () => {
        await stopTestServer();
    });

    it('validates the expectations of the Frontend', async () => {
        const opts = {
            provider: 'ScriptDrafts-GraphQL-API',
            providerBaseUrl: `${serverUrl}/graphql`,

            // Path to the JSON file generated by the frontend
            // In a real pipeline, this would be fetched from a Pact Broker URL
            pactUrls: [
                path.resolve(__dirname, '../../frontend/tests/pact/contracts/ScriptDrafts-Frontend-ScriptDrafts-GraphQL-API.json')
            ],

            // STATE HANDLERS: 
            // Pact will tell your backend "Hey, act like a user with ID user-123 exists"
            // You must seed your test database accordingly before Pact fires the request!
            stateHandlers: {
                'a user with ID user-123 exists': async () => {
                    // e.g., await UserModel.create({ id: 'user-123', name: 'Jane Doe', ... })
                    console.log('Seeded User 123 into test database');
                    return Promise.resolve('State Setup complete');
                },
                'user-123 has authored scripts': async () => {
                    // e.g., await ScriptModel.create({ authorId: 'user-123', title: 'Test Script' })
                    console.log('Seeded scripts for User 123');
                    return Promise.resolve('State Setup complete');
                },
                'users matching "jane" exist': async () => {
                    // Seed users matching the search criteria
                    return Promise.resolve('State Setup complete');
                },
            },
        };

        // 2. Run the Verification
        const verifier = new Verifier(opts);
        await verifier.verifyProvider();
        console.log('Pact Verification Successful! The Backend matches the Frontend contract.');
    });
});